sycls-admin-api/src/main/resources/application.yml
sycls-core/src/main/resources/application-core.yml
sycls-user-api/src/main/resources/application.yml

> Main Issue Number : #1
> Sub Issue Number : #2
> <br>
> resolved : #2
> 영향을 끼친 곳

♻️ refactor(환경): yml 파일 설정

---

api-test/admin/seat-test.http
sycls-admin-api/src/main/java/com/b1/place/PlaceAdapter.java
sycls-admin-api/src/main/java/com/b1/place/PlaceRestController.java
sycls-admin-api/src/main/java/com/b1/place/dto/SeatUpdateRequestDto.java
sycls-admin-api/src/main/java/com/b1/seat/SeatAdapter.java
sycls-admin-api/src/main/java/com/b1/seat/SeatController.java
sycls-admin-api/src/main/java/com/b1/seat/SeatRestController.java
sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
sycls-admin-api/src/main/java/com/b1/seat/dto/SeatAddRequestDto.java
sycls-admin-api/src/main/java/com/b1/seat/dto/SeatGetAllResponseDto.java
sycls-admin-api/src/main/java/com/b1/seat/dto/SeatGetResponseDto.java
sycls-common/src/main/java/com/b1/exception/customexception/SeatAlreadyDeletedException.java
sycls-common/src/main/java/com/b1/exception/customexception/SeatNotFoundException.java
sycls-common/src/main/java/com/b1/exception/errorcode/SeatErrorCode.java
sycls-core/src/main/java/com/b1/seat/SeatRepository.java
sycls-core/src/main/java/com/b1/seat/entity/Seat.java
sycls-core/src/main/java/com/b1/seat/entity/SeatStatus.java

> Main Issue Number : #29
> Sub Issue Number : #30, #31, #32, #33, #34
> <br>
> resolved : #30, #31, #32, #33, #34
> 좌석 등록, 전체조회, 상세(단건)조회 , 수정, 삭제
> 없음

🎉feature: 좌석 CRUD

---

sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
sycls-admin-api/src/main/java/com/b1/place/PlaceService.java
sycls-admin-api/src/main/java/com/b1/seat/SeatHelper.java
sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
sycls-common/src/main/java/com/b1/exception/customexception/ReviewAlreadyDeletedException.java
sycls-common/src/main/java/com/b1/exception/customexception/ReviewNotFoundException.java
sycls-common/src/main/java/com/b1/exception/errorcode/ReviewErrorCode.java
sycls-core/src/main/java/com/b1/review/ReviewQueryRepository.java
sycls-core/src/main/java/com/b1/review/dto/ReviewGetAllResponseDto.java
sycls-core/src/main/java/com/b1/review/entity/Review.java
sycls-core/src/main/java/com/b1/review/entity/ReviewStatus.java
sycls-user-api/src/main/java/com/b1/review/ReviewController.java
sycls-user-api/src/main/java/com/b1/review/ReviewHelper.java
sycls-user-api/src/main/java/com/b1/review/ReviewRestController.java
sycls-user-api/src/main/java/com/b1/review/ReviewService.java
sycls-user-api/src/main/java/com/b1/review/dto/ReviewAddRequestDto.java
sycls-user-api/src/main/java/com/b1/review/dto/ReviewUpdateRequestDto.java

> Main Issue Number : #43 
> Sub Issue Number : #44, #45, #46, #47
> <br>
> resolved : #44
> resolved : #45
> resolved : #46
> resolved : #47  
> 사용자의 리뷰 CRUD 기능 구현
> 없음

🎉feature: 사용자 리뷰 CRUD

---

sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
sycls-admin-api/src/main/java/com/b1/round/RoundService.java
sycls-core/src/main/java/com/b1/place/PlaceRepository.java
sycls-core/src/main/java/com/b1/seatgrade/SeatGradeQueryRepository.java

> Main Issue Number : #109 
> Sub Issue Number : #114 
> <br>
> resolved : #114 
> 회차 생성과 수정시 place 상태 감지 로직 추가
> place helper , placeQueryRepository

♻️ refactor: 회차 리펙토링

---

api-test/user/round-test.http
sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
sycls-core/src/main/java/com/b1/round/dto/ContentAndRoundGetResponseDto.java
sycls-user-api/src/main/java/com/b1/round/RoundHelper.java
sycls-user-api/src/main/java/com/b1/round/RoundRestController.java
sycls-user-api/src/main/java/com/b1/round/RoundService.java

> Main Issue Number : #119 
> Sub Issue Number : #120 
> <br>
> resolved : #120 
> 회차 단일 간단조회 기능 구현
> 영향을 끼친 곳

🎉 feat(#120): 회차 단일 간단 조회 기능 구현

---

sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
sycls-admin-api/src/main/java/com/b1/place/PlaceRestController.java
sycls-admin-api/src/main/java/com/b1/seat/SeatHelper.java
sycls-admin-api/src/main/java/com/b1/seat/SeatRestController.java
sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
sycls-admin-api/src/main/java/com/b1/seat/dto/SeatUpdateRequestDto.java
sycls-common/src/main/java/com/b1/exception/customexception/SeatCannotAddException.java
sycls-common/src/main/java/com/b1/exception/customexception/SeatCodeDuplicatedException.java
sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalCannotAddExcpetion.java
sycls-common/src/main/java/com/b1/exception/errorcode/SeatErrorCode.java
sycls-common/src/main/java/com/b1/exception/exceptionhandler/ApiExceptionHandler.java
sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
sycls-core/src/main/java/com/b1/seat/SeatRepository.java

> Main Issue Number : #110 
> Sub Issue Number : #111 , #112 ,  #113 
> <br>
> resolved : #111 
> resolved : #112 
> resolved : #113 
> 영향을 끼친 곳

♻️ refactor: 좌석 리펙토링

---

sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java
sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
sycls-admin-api/src/main/java/com/b1/place/PlaceService.java
sycls-admin-api/src/main/java/com/b1/place/dto/PlaceSearchCondRequestDto.java
sycls-core/src/main/java/com/b1/common/PageResponseDto.java
sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
sycls-core/src/main/java/com/b1/place/entity/Place.java

> Main Issue Number : #151 
> Sub Issue Number : #152 
> <br>
> resolved : #152 
> 공연장 리팩토링
> 관리자 - WebSecurityConfig

♻️ refactor(#152): 공연장 리팩토링

---

api-test/admin/content-test.http
api-test/admin/round-test.http
api-test/user/cast-test.http
api-test/user/content-test.http
sycls-admin-api/src/main/java/com/b1/category/CategoryRestController.java
sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java
sycls-admin-api/src/main/java/com/b1/content/ContentRestController.java

> Main Issue Number : #156 
> Sub Issue Number : #157 
> <br>
> resolved : #157 
> 카테고리와 콘텐츠 조회 부분 수정 및 시큐리티 컨피그 수정
> 시큐리티 컨피그 수정

🐛 bugfix(#157): 카테고리와 콘텐츠 조회부분 수정

---

sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java

> Main Issue Number : #163 
> 어드민 모듈에 있는 시큐리티컨피그 파일에 Bean 등록이 정상적으로 되어있지 않은 부분 수정

♻️ refactor(#163): Admin module SecurityConfig refactoring

---

sycls-admin-api/src/main/java/com/b1/config/EmailConfig.java
sycls-admin-api/src/main/java/com/b1/email/EmailService.java
sycls-admin-api/src/main/java/com/b1/security/JwtProvider.java
sycls-user-api/src/main/java/com/b1/config/EmailConfig.java
sycls-user-api/src/main/java/com/b1/email/EmailService.java
sycls-user-api/src/main/java/com/b1/security/JwtProvider.java

> Main Issue Number : #172 
> @Value 어노테이션 환경변수 명 수정

♻️ refactor(#172): @Value 어노테이션 환경변수 명 수정

---

sycls-admin-api/src/main/java/com/b1/user/UserRestController.java
sycls-user-api/src/main/java/com/b1/user/UserRestController.java

> Main Issue Number : #172
> UserRestController에 /user/me API URI 수정

♻️ refactor(#172): /user/me API URI 수정

---

sycls-admin-api/src/main/resources/application.yml
sycls-core/src/main/resources/application-core.yml
sycls-user-api/src/main/resources/application.yml

> Main Issue Number : #189
> Sub Issue Number : #190
> <br>
> resolved : #190
> 영향을 끼친 곳

♻️ refactor(#189): yml 파일 수정

---

sycls-admin-api/src/main/resources/application.yml
sycls-user-api/src/main/resources/application.yml

> Main Issue Number : #192
> Sub Issue Number : #193
> <br>
> resolved : #193
> 영향을 끼친 곳

♻️ refactor(#193): yml 파일 수정

---

sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
sycls-core/src/main/java/com/b1/round/dto/RoundInfoGetAdminResponseDto.java
sycls-core/src/main/java/com/b1/round/dto/RoundInfoGetUserResponseDto.java

> Main Issue Number : #196 
> Sub Issue Number : #197 
> <br>
> resolved : #197
> 쿼리에 반환값 추가
> 영향을 끼친 곳

♻️ refactor(#197): 쿼리에 반환값 추가

---

sycls-core/src/main/java/com/b1/config/RedisConfig.java

> Main Issue Number : #202
> Sub Issue Number : #203
> <br>
> resolved : #203
> 영향을 끼친 곳

♻️ refactor(#202): RedisConfig 업데이트

---

api-test/user/review-test.http
sycls-admin-api/src/main/java/com/b1/review/ReviewHelper.java
sycls-admin-api/src/main/java/com/b1/review/ReviewRestController.java
sycls-admin-api/src/main/java/com/b1/review/ReviewService.java
sycls-admin-api/src/main/java/com/b1/review/dto/ReviewSearchCondRequestDto.java
sycls-core/src/main/java/com/b1/review/ReviewQueryRepository.java
sycls-core/src/main/java/com/b1/review/dto/ReviewGetAdminResponseDto.java
sycls-core/src/main/java/com/b1/review/dto/ReviewGetAllResponseDto.java
sycls-core/src/main/java/com/b1/review/dto/ReviewGetUserResponseDto.java
sycls-user-api/src/main/java/com/b1/review/ReviewHelper.java
sycls-user-api/src/main/java/com/b1/review/ReviewRestController.java
sycls-user-api/src/main/java/com/b1/review/ReviewService.java

> Main Issue Number : #205 
> Sub Issue Number : #206 
> <br>
> resolved : #206 
> 리뷰 기능 쿼리 변경(페이지네이션 조건 추가), 동적쿼리 내용 변경, 리스폰스 반환값 추가, 동적쿼리 조건값 변경 email -> rating
> 영향을 끼친 곳

♻️ refactor(#206): 리뷰 쿼리 수정 및 리스폰스 값 변경

---

sycls-admin-api/src/main/java/com/b1/auth/CodeHelper.java
sycls-admin-api/src/main/java/com/b1/content/ContentService.java
sycls-admin-api/src/main/java/com/b1/email/EmailService.java
sycls-admin-api/src/main/java/com/b1/round/RoundHelper.java
sycls-admin-api/src/main/java/com/b1/ticket/TicketHelper.java
sycls-admin-api/src/main/java/com/b1/user/UserService.java
sycls-common/src/main/java/com/b1/constant/EmailConstants.java
sycls-common/src/main/java/com/b1/exception/customexception/EmailCodeException.java
sycls-common/src/main/java/com/b1/exception/customexception/EmailSendFailException.java
sycls-common/src/main/java/com/b1/exception/customexception/EncodingNotSupportedException.java
sycls-common/src/main/java/com/b1/exception/customexception/ReviewCannotAddException.java
sycls-common/src/main/java/com/b1/exception/customexception/SeatCannotAddException.java
sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalCannotAddException.java
sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalEmailException.java
sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalEmailServiceException.java
sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalFailException.java
sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalNotSupportedException.java
sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalPaymentException.java
sycls-common/src/main/java/com/b1/exception/errorcode/EmailErrorCode.java
sycls-common/src/main/java/com/b1/exception/exceptionhandler/ApiExceptionHandler.java
sycls-core/src/main/java/com/b1/content/entity/ContentStatus.java
sycls-core/src/main/java/com/b1/round/RoundRepository.java
sycls-core/src/main/java/com/b1/round/entity/RoundStatus.java
sycls-core/src/main/java/com/b1/ticket/TicketRepository.java
sycls-core/src/main/java/com/b1/ticket/entity/Ticket.java
sycls-core/src/main/java/com/b1/ticket/entity/TicketStatus.java
sycls-user-api/src/main/java/com/b1/auth/CodeHelper.java
sycls-user-api/src/main/java/com/b1/user/UserService.java

> Main Issue Number : #210 
> Sub Issue Number : #211 
> <br>
> resolved : #211 
> 공연 취소기능에 취소시 후속조치 기능 추가 및 리펙토링 (추후 결제취소가 가능하면 변경) 
> 글로벌 익셉션, EmailService, Ticket Entity Ticket Helper(admin-api)

♻️ refactor(#211): 공연기능 리펙토링

---

sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
sycls-core/src/main/java/com/b1/ticket/TicketQueryRepository.java
sycls-core/src/main/java/com/b1/ticket/dto/TicketGetAllDto.java
sycls-core/src/main/java/com/b1/ticket/dto/TicketGetDetailDto.java
sycls-core/src/main/resources/application-core.yml
sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
sycls-user-api/src/main/java/com/b1/ticket/TicketHelper.java
sycls-user-api/src/main/java/com/b1/ticket/TicketRestController.java
sycls-user-api/src/main/java/com/b1/ticket/TicketService.java
sycls-user-api/src/main/java/com/b1/ticket/dto/TicketGetAllUserResponseDto.java
sycls-user-api/src/main/java/com/b1/ticket/dto/TicketGetDetailCastResponseDto.java
sycls-user-api/src/main/java/com/b1/ticket/dto/TicketGetDetailUserResponseDto.java

> Main Issue Number : #213 
> Sub Issue Number : #214, #215
> <br>
> resolved : #214
> resolved : #215
> 좌석등급Helper

🎉 feat(#213): 티켓 조회

---

sycls-core/build.gradle
sycls-core/src/main/java/com/b1/config/RedisConfig.java
sycls-user-api/build.gradle
sycls-user-api/src/main/java/com/b1/ticket/TicketService.java
sycls-user-api/src/main/java/com/b1/ticket/dto/TicketGetDetailCastResponseDto.java
sycls-user-api/src/main/java/com/b1/ticket/dto/TicketGetDetailUserResponseDto.java

> Main Issue Number : #217 
> Sub Issue Number : #218
> <br>
> resolved : #218
> 영향을 끼친 곳

♻️ refactor(#217): 공연 조회

---

sycls-core/build.gradle
sycls-core/src/main/java/com/b1/config/RedisConfig.java
sycls-core/src/main/resources/application-core.yml

> Main Issue Number : #225
> Sub Issue Number : #226 
> <br>
> resolved : #226
> 영향을 끼친 곳

♻️ refactor(#226): yml 수정 및 사용하지 않는 의존성 제거

---

.github/workflows/cd-admin.yml
.github/workflows/cd-user.yml
appspec.yml
sycls-admin-api/Dockerfile
sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java
sycls-core/build.gradle
sycls-user-api/Dockerfile
sycls-user-api/src/main/java/com/b1/auth/AuthRestController.java
sycls-user-api/src/main/java/com/b1/config/WebSecurityConfig.java

> Main Issue Number : #170
> Sub Issue Number : #171 
> <br>
> resolved : #171 
> github workflows 디렉토리에 cicd관련 파일, dockerfile,  appspec.yml 생성
> 영향을 끼친 곳

🎉 feat: 배포 파일 생성

---

.github/workflows/cd-admin.yml
.github/workflows/cd-user.yml

> Main Issue Number : #233 
> Sub Issue Number : #234
> <br>
> resolved : #234 
> 배포파일수정
> 영향을 끼친 곳

🐛 bugfix: user github actions yml파일수정

---

sycls-admin-api/src/main/java/com/b1/seat/SeatHelper.java

> Main Issue Number : #237 
> Sub Issue Number : #240 
> <br>
> resolved : #240 
> 좌석 등록시 에러 해결
> 영향을 끼친 곳

🐛 bugfix(#240): 좌석 등록시 발생하는 에러 해결

---

.github/workflows/cd-user.yml

> Main Issue Number : #245 
> Sub Issue Number : #246 
> <br>
> resolved : #246 
> docker 실행 명령어 name 수정
> 영향을 끼친 곳

♻️ refactor(246): docker 실행 명령어 name 수정

---

sycls-admin-api/src/main/java/com/b1/round/RoundService.java
sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java

> Main Issue Number : #249 
> Sub Issue Number : #250 
> <br>
> resolved : #250 
> 회차의 공연장 변경시 좌석등급 비활성화
> 영향을 끼친 곳

🐛 bugfix(#250): 회차의 공연장 변경시 좌석등급 비활성화

---

.github/workflows/cd-user.yml
sycls-admin-api/src/main/java/com/b1/round/RoundService.java
sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java

회차에 등록된 공연장 변경시 등록해둔 좌석등급 비활성화처리

🎉 MERGE : dev merge

---

sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeRestController.java
sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeService.java
sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeAddRequestDto.java
sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeDeleteRequestDto.java
sycls-core/src/main/java/com/b1/seat/SeatRepository.java
sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
sycls-user-api/src/main/java/com/b1/review/ReviewHelper.java

> Main Issue Number : #255 
> Sub Issue Number : #256 
> <br>
> resolved : #256 
> 좌석/ 좌석등급 리팩토링
> 영향을 끼친 곳

♻️ refactor(256): 좌석 및 좌석 등급 리팩토링

---

sycls-core/src/main/java/com/b1/content/ContentQueryRepository.java

> Main Issue Number : #259 
> Sub Issue Number : #260 
> <br>
> resolved : #260 
> 공연 상태변경 기능 리펙터링
> 영향을 끼친 곳

Refactor/259 공연 상태변경 기능 리펙터링

---

api-test/admin/place-test.http
sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
sycls-admin-api/src/main/java/com/b1/place/PlaceRestController.java
sycls-admin-api/src/main/java/com/b1/place/PlaceService.java
sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
sycls-core/src/main/java/com/b1/place/dto/PlaceGetEnableResponseDto.java

> Main Issue Number : #265 
> Sub Issue Number : #266 
> <br>
> resolved : #266 
> selectbox에 들어갈 공연장 list 조회
> 영향을 끼친 곳

♻️ refactor(265): place전체조회(Enable)

---

sycls-admin-api/src/main/java/com/b1/category/CategoryHelper.java
sycls-admin-api/src/main/java/com/b1/category/CategoryRestController.java
sycls-admin-api/src/main/java/com/b1/category/CategoryService.java
sycls-core/src/main/java/com/b1/category/CategoryQueryRepository.java
sycls-core/src/main/java/com/b1/category/CategoryRepository.java
sycls-core/src/main/java/com/b1/category/dto/CategoryGetEnableResponseDto.java

> Main Issue Number : #267 
> Sub Issue Number : #268 
> <br>
> resolved : #268 
> 카테고리전체조회(Enable) 
> 영향을 끼친 곳

♻️ refactor(265): 카테고리전체조회(Enable) 

---

sycls-admin-api/src/main/java/com/b1/round/RoundService.java
sycls-admin-api/src/main/java/com/b1/round/dto/RoundAddRequestDto.java
sycls-common/src/main/java/com/b1/exception/customexception/InvalidDateTimeException.java
sycls-common/src/main/java/com/b1/exception/errorcode/RoundErrorCode.java

> Main Issue Number : #276 
> Sub Issue Number : #277 #278 
> resolved : #277 #278 
> 회차 sequence 검증추가
공연의 시작일이 지금 현재 시간보다 이전일 수 없게 변경
> 영향을 끼친 곳

♻️ refactor(276) : 회차기능 리펙토링

---

sycls-admin-api/build.gradle
sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerRestController.java
sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerService.java

> Main Issue Number : #272 
> Sub Issue Number : #281 
> <br>
> resolved : #281 
> 더미데이터 로직 추가
> 영향을 끼친 곳

🎉 feat(#281): 더미데이터 생성 로직 작성

---

sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerRestController.java
sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerService.java

> Main Issue Number : #286 
> Sub Issue Number : #287
> <br>
> resolved : #287
> 영향을 끼친 곳

♻️ refactor(#287): 더미 데이터 생성 api 업데이트

---

sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerRestController.java
sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerService.java
sycls-core/src/main/java/com/b1/round/RoundRepository.java
sycls-core/src/main/java/com/b1/seat/SeatRepository.java

> Main Issue Number : #메인 이슈 번호
> Sub Issue Number : #하위 이슈 번호
> <br>
> resolved : #하위 이슈 번호
> 영향을 끼친 곳

♻️ refactomr(#294): 더미 데이터 추가 업데이트

---

api-test/admin/datafaker-test.http
sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
sycls-core/src/main/java/com/b1/content/ContentQueryRepository.java
sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java

> Main Issue Number : #297 
> Sub Issue Number : #298 
> <br>
> resolved : #298 
> 좌석등급 더미데이터 등록 로직 수정
> 영향을 끼친 곳

♻️ refactor(#298): 좌석등급 더미데이터 등록 로직 수정

---

sycls-admin-api/src/main/java/com/b1/round/dto/RoundAddRequestDto.java

> Main Issue Number : #301 
> Sub Issue Number : #302 
> <br>
> resolved : #302 
> request dto valid 수정
> 영향을 끼친 곳

🐛 bugfix(#302): request dto valid 수정

---

sycls-admin-api/src/main/java/com/b1/content/ContentRestController.java
sycls-admin-api/src/main/java/com/b1/content/ContentService.java
sycls-admin-api/src/main/java/com/b1/seat/SeatRestController.java
sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
sycls-common/build.gradle
sycls-common/src/main/java/com/b1/exception/customexception/AddLockException.java
sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalInterruptedException.java
sycls-common/src/main/java/com/b1/exception/errorcode/CommonErrorCode.java
sycls-common/src/main/java/com/b1/exception/exceptionhandler/ApiExceptionHandler.java
sycls-core/build.gradle
sycls-core/src/main/java/com/b1/aop/AopForTransaction.java
sycls-core/src/main/java/com/b1/aop/CustomSpringELParser.java
sycls-core/src/main/java/com/b1/aop/DistributedLock.java
sycls-core/src/main/java/com/b1/aop/DistributedLockAop.java
sycls-user-api/build.gradle

> Main Issue Number : #312 
> Sub Issue Number : #313 
> <br>
> resolved : #313 
> 공연 추가 및 좌석 추가 기능에 Redisson 분산락 적용 동시성제어
> 공연 추가, 좌석 추가 기능

🎉 feat(#313): 등록 요청 동시성 제어
